services:
  db:
    image: postgres:16
    container_name: eduflow_db
    environment:
      POSTGRES_USER: eduflow
      POSTGRES_PASSWORD: eduflowpass
      POSTGRES_DB: eduflow
    ports:
      - "5433:5432"
    volumes:
      - eduflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduflow -d eduflow"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: eduflow_redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - eduflow_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  eduflow_db_data:
  eduflow_redis_data:
